### ISSUE TITLE
"Browse your pull requests" show blank page after opening an URL

### ISSUE THREAD

**Issue by doggy8088** [microsoft/azure-repos-vscode#535]
After I installed [Azure Repros](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team) and Signed in, I clicked on the **Browse your pull requests** icon:

![image](https://user-images.githubusercontent.com/88981/59176278-250f8580-8b8b-11e9-8532-0fc2df25db66.png)

My browser will open a url format like this:

```txt
https://dev.azure.com/willh/PartsUnlimited/_git/PartsUnlimited/pullrequests
```

Then the browser will show nothing. Completely blank. 

![image](https://user-images.githubusercontent.com/88981/59200854-bbfc3200-8bcb-11e9-9c28-97248886524f.png)

I checked the HTML source code. It do returned many content and all the HTTP status code are all 200.

Then I open F12 developer tool, I see the following error messages:

```
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://dev.azure.com/willh/PartsUnlimited/_git/PartsUnlimited/pullrequests' cannot be created in a document with origin 'https://dev.azure.com' and URL 'https://willh@dev.azure.com/willh/PartsUnlimited/_git/PartsUnlimited/pullrequests'.
    at serviceFactory._setState (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.viNhCOm3drsbimco.min.js:1:77117)
    at serviceFactory.replaceState (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.viNhCOm3drsbimco.min.js:1:75233)
    at serviceFactory._serviceStart (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.viNhCOm3drsbimco.min.js:1:75068)
    at Object._loadService (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.viNhCOm3drsbimco.min.js:1:8995)
    at Object.getService (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.viNhCOm3drsbimco.min.js:1:8278)
    at HTMLDocument.<anonymous> (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.viNhCOm3drsbimco.min.js:1:7067)
```

![image](https://user-images.githubusercontent.com/88981/59176989-3c4f7280-8b8d-11e9-82b3-5e5c671d88c5.png)

I think Azure Repros extension opened an URL that cause this problem. I dive deeper to see what's going on. I realized that the url contains an `willh@` prefix to the domain. That's why js produce error because security constraint.

![image](https://user-images.githubusercontent.com/88981/59200322-873bab00-8bca-11e9-979c-b3eec17110e7.png)

**Comment by BaileyMillerSSI** [comment]
For me removing the query string `?view=discussion` does the trick

**Comment by larryclaman** [comment]
Confirmed - I have also seen problem this as have teammates.
The workaround of the above comment 'removing the query string ?view=discussion does the trick' does temporarily solve the problem, but it is not a real fix.

**Comment by santu7github** [comment]
yes, I do have the same problem, removing the quesry string ?= view discussed dies the job. But it's not the decent amount of work I'll consider. Worked good for first 5 mins and bang I ran in to this issue. Have you got any update on the issue form the Team ?? Do you still facing the same issue?
