### ISSUE TITLE
Intellij IDEA 2020.1: KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED

### ISSUE THREAD

**Issue by ronvanpol** [microsoft/azure-repos-vscode#617]
I am trying to get the Azure Devops plugin working in IDEA 2020.1. Regardless of local workspaces, server workspaces, different authentication methods I keep getting the following error:

![image](https://user-images.githubusercontent.com/5981708/79765327-c0829280-8326-11ea-8e66-b89c89e6ddc8.png)

The event log states:

com.microsoft.alm.plugin.external.exceptions.WorkspaceCouldNotBeDeterminedException: KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.throwIfError(FindWorkspaceCommand.java:135)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:26)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

**Comment by maksym-plotnikov** [comment]
Same here
